# Generated by Django 4.1.5 on 2023-06-02 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
            options={"verbose_name_plural": "Categorias", "ordering": ("nome",),},
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("marca", models.CharField(blank=True, max_length=255, null=True)),
                ("modelo", models.CharField(blank=True, max_length=255, null=True)),
                ("tamanho", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "unid_por_embalagem",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("descrição", models.TextField(blank=True, null=True)),
                ("preço", models.FloatField()),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="produto_imagens"
                    ),
                ),
                ("em_estoque", models.BooleanField(default=False)),
                ("data_criação", models.DateTimeField(auto_now_add=True)),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="item.categoria",
                    ),
                ),
            ],
            options={"ordering": ("nome",),},
        ),
    ]
